### ISSUE TITLE
[API] Elasticsearch should'nt be a direct dependency

### ISSUE THREAD

**Issue by jmaupetit** [openfun/warren#102]
## Bug Report

**Expected behavior/code**
Warren's API no longer relies on Elasticsearch, it should not be a direct dependency.

**Actual Behavior**
Removing Elasticsearch dependency on the API service crashes the server.

**Environment**
- Ralph version: at least 3.8+

**Possible Solution**
Wait for a new Ralph release that fixes this issue (e.g. `v4.0.0` :crossed_fingers:)

**Comment by wilbrdt** [comment]
Fixed by #201
